### ISSUE TITLE
Feature Request: Text is small on mobile devices

### ISSUE THREAD

**Issue by rgeorgebu** [austinrovge/austinrovge.dev#12]
Hey there!

Love the site, however I do a lot of web browsing from my phone - would it be possible to bump up the text size in the name of readability and UX?

Thanks!

## Steps to Reproduce:

1. Open website on mobile device

## Artifacts

![image](https://user-images.githubusercontent.com/22624700/149552535-8037b78a-0179-41ef-bcb8-27e92f683d23.png)

**Comment by arovge** [comment]
Hi @rgeorgebu! Thanks for bringing this to my attention, the site definitely isn't accessible on smaller screens from that screenshot.

I've pushed some styling improvements in #13, could you look at [this dev deployment link](https://8cca8232.ajr-dev.pages.dev/) and let me know what you think?

**Comment by rgeorgebu** [comment]
Looks much better - but maybe bump it up bit more even. Also you may want to check the margin/padding of your social links at the bottom of the page. Thanks for looking into this 😄

![image](https://user-images.githubusercontent.com/22624700/151715392-68a6352a-43e5-425e-85df-defa5d18b66d.png)

**Comment by arovge** [comment]
Thats great that it's much more readable now! I've pushed some more commits with more styling improvements and merged them into `main`. Let me know if you have anymore styling suggestions!
